name: background_sms
description: The main purpose is to send sms from background and headless.
version: 0.0.4
homepage: https://github.com/shinewanna/BackgroundSmsPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.j.background_sms
        pluginClass: BackgroundSmsPlugin
      ios:
        pluginClass: BackgroundSmsPlugin
